@startuml

skinparam {
    Style strictuml
    RoundCorner 5
    ' use characters instead of icons for showing visibility
    ClassAttributeIconSize 0
    Database {
	' the default border no longer matches the normal colours (bug?), so fix this
	BorderColor #A80036
    }
    Sequence {
	' make activations yellow too
	LifeLineBackgroundColor #FDFDCD

	' make stereotypes less ugly
	Stereotype {
		Font {
			Size 11
			Style plain
		}
	}
    }
}
 
class "Customer" as customer {
    -customerId : Integer <<unique>> <<generated>>
    -username : String <<unique>>
    -firstName : String
    -lastName : String
    -password : String
    -phoneNumber : String
    -emailAddress : String
    '-card_details? 
  --
}

class "Subscription" as sub {
    -subscriptionId : Integer <<unique>> <<generated>>
    -name : String
    -type: Boolean
    -subscriptionPrice : BigDecimal
    -desciption: String
    -companyName: String
    -dueDate : LocalDateTime
    -issueDate : LocalDateTime
  --
}

customer --> "-subscriptions\n0..*" sub


@enduml
